"""Maintenance Troubleshooting Engine: public API.

Only names re-exported here are public. Internal modules must not be
imported by host-application adapters.
"""

from maintenance_troubleshooting.config import (
    EmbeddingConfig,
    EngineConfig,
    InputConfig,
    NormalizationConfig,
    OutputConfig,
    ScoringConfig,
    SimilarityConfig,
    TextMiningConfig,
)
from maintenance_troubleshooting.domain import (
    DEFAULT_PROBABILITY_SEMANTICS,
    CauseProbability,
    Confidence,
    Equipment,
    EvidenceScore,
    FailureInterpretation,
    FailureMechanism,
    FailureMode,
    FailureProvenance,
    MaintenanceRecord,
    OccurrenceRate,
    ProbabilityMethod,
    RecommendedAction,
    RelevanceBasis,
    RepairEvidence,
    SupportBreakdown,
    TechnicalTree,
    TroubleshootingCause,
    TroubleshootingGuide,
    normalize_probabilities,
)
from maintenance_troubleshooting.inputs import (
    ColumnMapping,
    ExcelMaintenanceReader,
    InputReport,
    PrefixNumberRecordId,
    ReadResult,
    RecordIdStrategy,
    ResolvedMapping,
    SchemaReport,
)
from maintenance_troubleshooting.outputs import TroubleshootingKnowledgeBase
from maintenance_troubleshooting.pipeline import (
    AnalysisResult,
    CauseRanker,
    EvidenceQuery,
    EvidenceSource,
    analyze_workbook,
)
from maintenance_troubleshooting.quality import (
    DataQualityReport,
    DuplicateDetector,
    DuplicateGroup,
    FailureModeConsistencyCheck,
    IssueSeverity,
    MissingFieldAnalysis,
    RecordIssue,
    RecordValidator,
    TextQualityAssessment,
)
from maintenance_troubleshooting.similarity import (
    TechnicalSimilarityCategory,
    TechnicalSimilarityScorer,
    classify_technical_similarity,
)
from maintenance_troubleshooting.text import (
    AliasMap,
    CharacterNGramSimilarity,
    EmbeddingProvider,
    SimpleTokenizer,
    TextCanonicalizer,
    TextNormalizationOptions,
    TextNormalizer,
    TextSimilarity,
    Tokenizer,
    TokenSetSimilarity,
)
from maintenance_troubleshooting.version import __version__

__all__ = [
    "AliasMap",
    "AnalysisResult",
    "CauseProbability",
    "CauseRanker",
    "CharacterNGramSimilarity",
    "ColumnMapping",
    "Confidence",
    "DEFAULT_PROBABILITY_SEMANTICS",
    "DataQualityReport",
    "DuplicateDetector",
    "DuplicateGroup",
    "EmbeddingConfig",
    "EmbeddingProvider",
    "EngineConfig",
    "Equipment",
    "EvidenceQuery",
    "EvidenceScore",
    "EvidenceSource",
    "ExcelMaintenanceReader",
    "FailureInterpretation",
    "FailureMechanism",
    "FailureMode",
    "FailureModeConsistencyCheck",
    "FailureProvenance",
    "InputConfig",
    "InputReport",
    "IssueSeverity",
    "MaintenanceRecord",
    "MissingFieldAnalysis",
    "NormalizationConfig",
    "OccurrenceRate",
    "OutputConfig",
    "PrefixNumberRecordId",
    "ProbabilityMethod",
    "ReadResult",
    "RecordIdStrategy",
    "RecordIssue",
    "RecordValidator",
    "RecommendedAction",
    "RelevanceBasis",
    "RepairEvidence",
    "ResolvedMapping",
    "SchemaReport",
    "ScoringConfig",
    "SimilarityConfig",
    "SimpleTokenizer",
    "SupportBreakdown",
    "TechnicalSimilarityCategory",
    "TechnicalSimilarityScorer",
    "TechnicalTree",
    "TextCanonicalizer",
    "TextMiningConfig",
    "TextNormalizationOptions",
    "TextNormalizer",
    "TextQualityAssessment",
    "TextSimilarity",
    "TokenSetSimilarity",
    "Tokenizer",
    "TroubleshootingCause",
    "TroubleshootingGuide",
    "TroubleshootingKnowledgeBase",
    "__version__",
    "analyze_workbook",
    "classify_technical_similarity",
    "normalize_probabilities",
]
